function inp_struct = memri_log(inp_struct, varargin)
% struct or log-data = memri_log(struct.filepath, varargin)
%
% Writes log-data to file. Input structure requires field "filepath" and 
% will return the same struct with an (updated) log-field plus an instance
% number field. The latter is used to track the log-file by log filename:
%   log-file = filepath + instance# .log
%
% The returned structure can be used to keep logging to the same log-file.
%
% NB. Date and time are appended to the start of each log-line.
%
% input
%   fpout:      - Struct with field(s) .filepath and optionally a .log-
%                 and an .instance -field. If .filepath is absent, the
%                 log-file is saved as instance.log in the current
%                 MATLAB working directory. 
%                 Instance is a date-time string generated by memri_log(): 
%                 year.month.day.HMS and used to identify log-instances.
%
%                 Opt: if inp_struct is '\*' the output will be the input
%                 log-lines processed as default without saving to file.
%
%                 Opt: filepath for log-file. The instance number will be
%                 ignored and only a cell-list with log-data is returned.
%
%   varargin:   log-data input as string or integers. Data will be 
%               converted to string and every variable input argument will 
%               be treated as a single line. 
%
% Example: 
% memri = memri_log(memri, 'WSVD applied. Noise-mask:', size(data,1)/6);
% log = memri_log('\mylogile.log', 'Method applied.');
%
%
% Quincy van Houtum, v12.2025
% quincyvanhoutum@gmail.com

% // --- Process input
ninp = numel(varargin);

% Check for struct or string input fpout.
inpispath = ~isstruct(inp_struct);          % < Input is Path > %
if inpispath, fpin = inp_struct; inp_struct.filepath = fpin; end

% Check if doSave is enabled
doSave = 1; if inpispath && strcmp(fpin, '\*'), doSave = 0; end

% Add log-memri instance: month-day-hour-minutes-seconds.
if ~inpispath && ~isfield(inp_struct, 'instance')
    inp_struct.instance = string(datetime('now','Format','yyyy.MM.dd.HHmmss'));
end

% // --- Log filename

% Log-file path
if ~inpispath && isfield(inp_struct, 'filepath')
    [fp, fn, ~] = fileparts(inp_struct.filepath); 
    fplog = strcat(fp, '\', fn, '_', inp_struct.instance, '.log');
elseif inpispath
    fplog = inp_struct.filepath;
else
    fplog = strcat(inp_struct.instance,'.log');
end

% // --- Log input processing & write to file

% Add log from input if its a new file
if ~isfile(fplog) && isfield(inp_struct, 'log') && doSave
    % Open file ID
    fid = fopen(fplog, 'a+');

    % Write current log-data to file
    for kk = 1:numel(inp_struct.log)
        fprintf('%s/n', inp_struct.log{kk});
    end
    fclose(fid);
end

% Add new lines
linesnew = cell(1,ninp);
for kk = 1:ninp
   val = varargin{kk}; 
   
   % Convert non-char input
   if ~ischar(val) % Convert to a string if not char.
       val = arrayfun(@num2str, val, 'UniformOutput',0);
       if numel(val) > 1, val = strjoin(val{:}, ' '); else, val = val{:}; end
   end 

   % Write to file
   linesnew{kk} = sprintf('%s - %s %s/n', ...
       datetime('now','Format','HH:mm:ss'), val);  
end

% Open file ID and write to file
if doSave
    fid = fopen(fplog, 'a+'); 
    for kk = 1:ninp
        fprintf(fid, '%s\n', linesnew{kk});
    end
    fclose(fid);
end


% // --- Create function output

% Read log-file or memri-log
lines = {};
if ~inpispath && isfield(inp_struct,'log'), lines = inp_struct.log; end

% Set output
if inpispath, inp_struct = cat(1,lines(:), linesnew(:)); 
else,         inp_struct.log = cat(1,lines(:), linesnew(:)); 
end


