function inp_struct = memri_log(inp_struct, varargin)
% struct or log-data = memri_log(struct, varargin)
%
% Convert log-input to logging format and write to file. Input structure 
% uses fields "filepath", "log" and "instance".
% Will return the struct with an (updated) log-field plus an instance
% number field. The latter is used to track the log-file by log filename:
% log filename = filepath + instance# .log
%
% The returned structure can be used to keep logging to the same log-file.
%
% Instance is a date-time string generated by memri_log() to identify 
% log-instances: year.month.day.HMS
%
% NB. Time (HH:MM:SS) is appended to the start of each log-line.
%
% input
%   inp_struct: - Struct with field(s) .filepath, .log and instance.
%
%                 If filepath and instance exist:
%                       Append log input to log-file.
%                 If log-field has data with new log-instance:
%                       Adds log-field content to new file before appending
%                       log-data input.
%                 If instance is absent:
%                       An instance number is generated and thus a new
%                       log-file will be written to.
%                 If fieldpath is absent:
%                       Log-file saved as "instance.log"               
%               
%                 * Disable saving to file:
%                 if the first varargin input equals '\*' the output will 
%                 be the input log-data processed as default without saving
%                 to file.
%
%                 * Input a log its filepath:
%                 The inp_struct is a filepath string for a log-file. The 
%                 instance number is not used at all and only a cell-list 
%                 with log-data is returned. Any log-data input will be
%                 appended with the /* argument removed.
%
%   varargin:   - log-data input as string or integers. Data will be 
%                 converted to string and every variable input argument 
%                 will be treated as a single line. 
%                 NB. Matrices and other multi-dimensional variables are
%                 not recommended.
%
% Examples: 
%   memri.filepath = 'C:\CSI_Converted.mat';
%   memri = memri_log(memri, 'WSVD applied. Noise-mask:', size(data,1)/6);
% or
%   log = memri_log('\mylogile.log', 'Method applied.');
%
%
% Quincy van Houtum, v01.2026
% quincyvanhoutum@gmail.com

% // --- Process input


% Check for struct or string input fpout.
inpispath = ~isstruct(inp_struct);          % < Input is Path > %
if inpispath, fpin = inp_struct; inp_struct.filepath = fpin; end

% Check if doSave must be disabled
ninp = numel(varargin); doSave = 1; 
if strcmp(varargin(1),'\*') % Removed from input if true
    doSave = 0; if ninp > 1, varargin(1) = []; ninp = numel(varargin); end
end

% Add log-memri instance: month-day-hour-minutes-seconds.
if ~inpispath && ~isfield(inp_struct, 'instance')
    inp_struct.instance = string(datetime('now','Format','yyyy.MM.dd.HHmmss'));
end

% // --- Log filename

% Log-file path
if ~inpispath && isfield(inp_struct, 'filepath')
    [fp, fn, ~] = fileparts(inp_struct.filepath); 
    fplog = strcat(fp, '\', fn, '_', inp_struct.instance, '.log');
elseif inpispath
    fplog = inp_struct.filepath;
else
    fplog = strcat(inp_struct.instance,'.log');
end

% // --- Analyse and Prepare Log-Data

% Add log from input if its a new file
if ~isfile(fplog) && isfield(inp_struct, 'log') && doSave
    % Open file ID
    fid = fopen(fplog, 'a+');
    if fid == -1, return; end
    
    % Write current log-data to file
    for kk = 1:numel(inp_struct.log)
        fprintf(fid, '%s\n', inp_struct.log{kk});
    end
    fclose(fid);
end

% Add new lines
linesnew = cell(1,ninp);
for kk = 1:ninp
   val = varargin{kk}; 
   
   % Convert non-char input
   if ~ischar(val) % Convert to a string if not char.
       val = arrayfun(@num2str, val, 'UniformOutput',0);
       if numel(val) > 1, val = strjoin(val{:}, ' '); else, val = val{:}; end
   end 

   % Write to file
   linesnew{kk} = sprintf('%s - %s %s/n', ...
       datetime('now','Format','HH:mm:ss'), val);  
end


% // --- Open file ID and write to file
if doSave
    fid = fopen(fplog, 'a+'); % File ID
    if fid == -1
        fprintf('memri_log: Could not write to txt-file.\n'); return; 
    end

    % Write to file
    for kk = 1:ninp, fprintf(fid, '%s\n', linesnew{kk}); end
    fclose(fid);
end


% // --- Create function output

% Read log-file or memri-log
lines = {};
if ~inpispath && isfield(inp_struct,'log'), lines = inp_struct.log; end

% Set output
if inpispath, inp_struct = cat(1,lines(:), linesnew(:)); 
else,         inp_struct.log = cat(1,lines(:), linesnew(:)); 
end


