

fh = figure('Name','MeMRI PTB', 'Tag', 'MEMRI-PTB',...
            'NumberTitle','off', 'MenuBar','none', 'ToolBar','none',...
            'Color','k');
gui = guidata(fh);

% System information
scrsz = get(0, 'ScreenSize'); scrsz(1:2) = [];
dpath = cd; % Current default path.

% Title text % Dropdown % Button % Tickbox

gui.ch = uicontrol(fh, 'Style',	'checkbox', ...
    'BackgroundColor', 'k', 'String', 'Title', ...
    'FontSize', 12,  'FontWeight','bold');

gui.pu = uicontrol(fh,'Style','popupmenu', ...
    'String', {'Method 1', 'Method 2'});

gui.lb.main = uicontrol(fh, 'Style', 'listbox', ...
    'unit', 'normalized', 'Position', [0 0  1 1], ...
    'BackgroundColor', 'k');